### PR TITLE
Adding script to reformat STRs.tsv output

### PR DESCRIPTION
**Pull request by wdecoster**
This pull requests adds a script to reformat the STRs.tsv output:

- Creates a pivot table listing the samples side by side
- adding a variant identifier based on location and repeatunit
- adding aggregate columns for e.g. maximal bpInsertion and minimal p_adj
- sorting is possible on chromosomal location or significance (p_adj)

TODO: add gene annotation

### CODE REVIEW

**Comment by hdashnow** [comment]
Works for me. Is this ready to merge? I see a "TODO" comment.

**Comment by wdecoster** [comment]
Yes, it's ready to merge in my opinion. That TODO would be useful I believe but is not anything that's high on my list.

**Comment by hdashnow** [comment]
Thanks for sharing the script :)

**Comment by wdecoster** [comment]
Hope it can be useful - feedback is welcome!

**Pull request merged**
